<<<<<<< HEAD
<<<<<<< HEAD
theme: jekyll-theme-slate
title: Flask Electron
=======
theme: jekyll-theme-slate
>>>>>>> dec7fd3... Set theme jekyll-theme-slate
=======
theme: jekyll-theme-slate
title: "Flask Electron"
>>>>>>> 3921706... github pages content
